### ISSUE TITLE
Model classes in wpstarter

### ISSUE THREAD

**Issue by ongtt** [wpstarter/framework#27]
I find a library get data from wordpress database is Corcel. Can i use it in wpstarter?

**Comment by as247** [comment]
Yes, you can use it inside wpstarter, but Corcel will make separated database connection and it's not recommended. Instead you may try to just copy Model from Corcel
https://github.com/corcel/corcel/tree/6.0/src/Model
and change to extend class from WpStarter\Database\Eloquent\Model
