### ISSUE TITLE
Seeders does not seem to work

### ISSUE THREAD

**Issue by fabarea** [wpstarter/framework#69]
Whenever I run command : 

```
php artisan migrate:fresh --seed
```

I get the following error:

```shell
In DatabaseServiceProvider.php line 89:

  Class "Faker\Factory" not found
```

I don't know how to fix it, but we can see the missing import in `vendor/wpstarter/framework/src/WpStarter/Database/DatabaseServiceProvider.php`

<img width="1319" alt="image" src="https://github.com/wpstarter/framework/assets/620730/736f4653-05ed-4031-8da5-a065ec8b4517">

WpStarter version: v1.5.7

**Comment by as247** [comment]
You need to install fakerphp/faker package https://packagist.org/packages/fakerphp/faker
"require-dev": {
    "fakerphp/faker": "^1.22.0",
    // ...
}

**Comment by fabarea** [comment]
@as247 thanks! I have taken the liberty of opening a pull request for the documentation.

https://github.com/wpstarter/docs/pull/11
